@shopify_version={{$dotenv SHOPIFY_VERSION}}
@domain={{$dotenv SHOPIFY_DOMAIN}}
@shopify_key={{$dotenv SHOPIFY_KEY}}
@product_id={{$dotenv PRODUCT_ID}}

###
POST https://{{domain}}.myshopify.com/admin/api/{{shopify_version}}/graphql.json
Content-Type: application/json
X-Shopify-Access-Token: {{shopify_key}}
X-REQUEST-TYPE: GraphQL

query productSearchById($gid: ID!) {
  product(id: $gid) {
    id
    handle
    productType
    variants(first: 5) {
      edges {
        node {
          id
        }
      }
    }
  }
}

{
  "gid": "gid://shopify/Product/{{product_id}}
}
