@api_version={{$dotenv SHOPIFY_VERSION}}
@shop_domain={{$dotenv SHOPIFY_DOMAIN}}
@shopify_token={{$dotenv SHOPIFY_TOKEN}}
@product_id={{$dotenv PRODUCT_ID}}

###
POST https://{{shop_domain}}.myshopify.com/admin/api/{{api_version}}/graphql.json
Content-Type: application/json
X-Shopify-Access-Token: {{shopify_token}}
X-REQUEST-TYPE: GraphQL

query ListSellingPlansFromProduct($id: ID!) {
  product(id: $id) {
    sellingPlanGroups (first: 2) {
      nodes {
        appId
        id
        productCount
        productVariantCount
        sellingPlans (first: 10) {
          nodes {
            name
            id
          }
        }
      }
    }
  }
}

{
  "id": "gid://shopify/Product/{{product_id}}"
}

