PUT https://{{$dotenv SHOPIFY_STORE}}.myshopify.com/admin/api/{{$dotenv SHOPIFY_API_VERSION}}/orders/{{$dotenv ORDER_ID}}.json
X-Shopify-Access-Token: {{$dotenv SHOPIFY_API_KEY}}
Content-Type: application/json

{
  "order": {
    "id": {{$dotenv ORDER_ID}},
    "tags":"External, Inbound, Outbound"
  }
}
