@api_version={{$dotenv SHOPIFY_VERSION}}
@domain={{$dotenv SHOPIFY_DOMAIN}}
@token={{$dotenv SHOPIFY_TOKEN}}
@amount={{$dotenv AMOUNT}}

###
POST https://{{domain}}.myshopify.com/admin/api/{{api_version}}/graphql.json
Content-Type: application/json
X-Shopify-Access-Token: {{token}}
X-REQUEST-TYPE: GraphQL

mutation appCreditCreate($amount: MoneyInput!, $description: String!, $test: Boolean!) {
  appCreditCreate(amount: $amount, description: $description, test: $test) {
    appCredit {
      id
      test
    }
    userErrors {
      field
      message
    }
  }
}

{
  "amount": {
    "amount": "{{amount}}",
    "currencyCode": "USD"
  },
  "description": "Application credit for refund",
  "test": true
}

###
