@api_version={{$dotenv SHOPIFY_VERSION}}
@domain={{$dotenv SHOPIFY_DOMAIN}}
@token={{$dotenv SHOPIFY_TOKEN}}

###
GET https://{{domain}}.myshopify.com/admin/api/{{api_version}}/shop.json
Content-Type: application/json
X-Shopify-Access-Token: {{token}}
