@api_version={{$dotenv SHOPIFY_VERSION}}
@domain={{$dotenv SHOPIFY_DOMAIN}}
@token={{$dotenv SHOPIFY_TOKEN}}

###
@namespace={{$dotenv NAMESPACE}}
@key={{$dotenv KEY}}
@resource_type=Shop
# Product, Collection, Order, Page, Blog, Article, Customer
@ownerId=gid://shopify/{{resource_type}}/{{$dotenv RESOURCE_ID}}
@type={{$dotenv TYPE}}
@value={{$dotenv VALUE}}


###
POST https://{{domain}}.myshopify.com/admin/api/{{api_version}}/graphql.json
Content-Type: application/json
X-Shopify-Access-Token: {{token}}
X-REQUEST-TYPE: GraphQL

mutation metafieldsSet($metafields: [MetafieldsSetInput!]!) {
  metafieldsSet(metafields: $metafields) {
    metafields {
      # Metafield fields
      id
      ownerType
      reference
      value
      owner {
        __typename
      }
    }
    userErrors {
      field
      message
    }
  }
}

{
  "metafields": [
    {
      "namespace": "{{namespace}}",
      "key": "{{key}}",
      "ownerId": "{{ownerId}}",
      "type": "{{type}}",
      "value": "{{value}}"
    }
  ]
}




### 

curl --request POST \
  --url https://recharge-crbn8-mock.myshopify.com/admin/api/2022-07/graphql.json \
  --header 'content-type: application/json' \
  --header 'user-agent: vscode-restclient' \
  --header 'x-shopify-access-token: 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' \
  --data '{"query":"mutation metafieldsSet($metafields: [MetafieldsSetInput!]!) {\n  metafieldsSet(metafields: $metafields) {\n    metafields {\n      id\n      ownerType\n      reference\n      value\n      owner {\n        __typename\n      }\n    }\n    userErrors {\n      field\n      message\n    }\n  }\n}","variables":{"metafields":[{"namespace":"algolia_search","key":"cars","ownerId":"gid://shopify/Shop/47976251554","type":"json_string","value":"{ \"name\": \"Alfa Romeo\", \"value\": \"Alfa Romeo\" }"}]}}'