
@domain={{$dotenv SHOPIFY_DOMAIN}}
@api_version={{$dotenv SHOPIFY_VERSION}}
@amount=10.00
@token={{$dotenv SHOPIFY_TOKEN}}
@description=Super Mega Plan 1000 emails

###
POST https://{{domain}}.myshopify.com/admin/api/{{api_version}}/graphql.json
Content-Type: application/json
X-Shopify-Access-Token: {{token}}
X-REQUEST-TYPE: GraphQL

mutation appUsageRecordCreate($lineItemId: ID!, $price: MoneyInput!, $description: String!) {
  appUsageRecordCreate (subscriptionLineItemId: $lineItemId, price: $price, description: $description) {
    appUsageRecord {
      id
      price {
        amount
      }
    }
    userErrors {
      field
      message
    }
  }
}

{
  "lineItemId": "gid://shopify/AppSubscriptionLineItem/{{$dotenv SUBSCRIPTION_LINE_ITEM_ID}}?v=1&index=0",
  "price": {
    "amount": "{{amount}}",
    "currencyCode": "USD"
  },
  "description": "{{description}}"
}


###
POST https://{{domain}}.myshopify.com/admin/api/{{api_version}}/graphql.json
Content-Type: application/json
X-Shopify-Access-Token: {{token}}
X-REQUEST-TYPE: GraphQL

mutation {
  appUsageRecordCreate(
    subscriptionLineItemId: "gid://shopify/AppSubscriptionLineItem/{{$dotenv SUBSCRIPTION_LINE_ITEM_ID}}?v=1&index=0"
    description: "{{description}}",
    price: { amount: {{amount}}, currencyCode: USD }
  ) {
    userErrors {
      field
      message
    }
    appUsageRecord {
      id
    }
  }
}

###