# SHOPIFY_STORE=
# SHOPIFY_API_KEY=
# CALCULATED_ORDER=

###
POST https://{{$dotenv SHOPIFY_STORE}}.myshopify.com/admin/api/2021-07/graphql.json
Content-Type: application/json
X-Shopify-Access-Token: {{$dotenv SHOPIFY_API_KEY}}
X-REQUEST-TYPE: GraphQL

mutation orderEditCommit($id: ID!) {
  orderEditCommit(id: $id) {
    order {
      name,
			id
    }
    userErrors {
      field
      message
    }
  }
}

{
  "id": "gid://shopify/CalculatedOrder/{{$dotenv CALCULATED_ORDER}}",
  "notifyCustomer": false,
  "staffNote": "Order edit API"
}
