###
POST https://{{$dotenv SHOP_NAME}}.myshopify.com/admin/api/{{$dotenv SHOPIFY_API_VERSION}}/blogs.json
Content-Type: application/json
X-Shopify-Access-Token: {{$dotenv SHOPIFY_ACCESS_TOKEN}}

{
  "blog": {
    "title": "Apple main blog",
    "metafields": [
      {
        "key": "sponsor",
        "value": "Shopify",
        "type": "single_line_text_field",
        "namespace": "global"
      }
    ]
  }
}
