module.exports = {
    "vendors": [
        "1sicnoma",
        "2mzdesign",
        "8BitHobo",
        "AJ Paglia",
        "APSketches",
        "Aaron A. Fimister",
        "Abigail Larson",
        "Adams Pinto",
        "Adelaidelia",
        "AdmConnor",
        "Adrian Filmore",
        "Aegis",
        "AlanBao",
        "AlbertoArni",
        "Albo1980",
        "Alease",
        "Alex Eckman-Lawn",
        "Alex Red",
        "Alex Solis",
        "AlexRoivas",
        "Alexhefe",
        "Aliadotony",
        "Alundrart",
        "AlynSpiller",
        "Amdy",
        "Andres Yeah",
        "AndreusD",
        "AndrewKwan",
        "Andriu",
        "Angoes25",
        "Apgar Arts",
        "Arcanito",
        "Archymedius",
        "Arinesart",
        "Arson",
        "Art_Of_One",
        "Ashley Hay",
        "Asyram",
        "AtomicRocket",
        "AudreyBenjaminsen",
        "AustinJames",
        "AutoSave",
        "Azafran",
        "BWdesigns",
        "BadEye",
        "Bamboota",
        "Barbadifuoco",
        "Bats on the Brain",
        "Be Human[e] Apparel",
        "Beardy Graphics",
        "BeastPop",
        "Belle Dee",
        "Betmac",
        "Beware_1984",
        "Binoftrash",
        "BlackJack-AD",
        "BlancaVidal",
        "Blue_37",
        "Bo Bradshaw",
        "Boggs Nicolas",
        "Bohdan Bykon",
        "Brinkerhoff",
        "Bruno Cezar",
        "Buby87",
        "Buck Rogers",
        "Buzatron",
        "BuzzArt",
        "C0y0te7",
        "Caffein Art",
        "CappO",
        "Captain Ribman",
        "Cattoc_C",
        "CharlieB98",
        "ChetArt",
        "ChocolateRaisinFury",
        "Chris Wahl",
        "Chriswithata",
        "Cinnamoron",
        "Clarck Art",
        "ClaudiaSG",
        "ClayGrahamArt",
        "Clint Kadera",
        "CoD Designs",
        "Coconut_Design",
        "Coinbox Tees",
        "Colin Lawler",
        "CorinnaSchlachter",
        "Corrose",
        "CoryDesigns",
        "CoryFreeman",
        "Crab-Metalitees",
        "Creative Outpouring",
        "Crumblin' Cookie",
        "CuckooArtDesign",
        "CupidsArt",
        "D-Artist",
        "D4N13L",
        "DCLawrence",
        "DClawrance",
        "DIENZOART",
        "DJKopet",
        "Daeron",
        "Daisyart-lab",
        "Dan Mumford",
        "Dar'Qaris",
        "DarthBader",
        "DauntlessDS",
        "Dave Perillo",
        "David Olenick",
        "DeadFrog",
        "DeepFriedArt",
        "Dennis Hansbury",
        "DiJay",
        "Diana Roberts",
        "DianaSprinkle",
        "Digital Magician",
        "DinoMike",
        "DoOomcat",
        "DoctorRoboto",
        "Domii",
        "Donnie",
        "DonovanAlex",
        "DoodleDee",
        "DrMonekers",
        "Dracortis",
        "Drew Wise",
        "Dulcie Doodles",
        "Eduvieirart",
        "Eilex Design",
        "El Black Bat",
        "Emilie_B",
        "EnaGrapher",
        "Eozen",
        "Eugene Kaik",
        "Ewel",
        "Eyesore427",
        "Fearcheck",
        "FelinkScratch",
        "FernandoSala",
        "Firebeard",
        "Firebrander",
        "Fishbiscuit",
        "Fishmas",
        "Fle",
        "Fluffins",
        "FrancisMacomber",
        "FreshFleur",
        "Fuacka",
        "FunTimesTees",
        "GEEKsomniac",
        "GODZILLARGE",
        "GallifreyaDs",
        "GamerPrint",
        "Gamma-Ray",
        "Gary McElkerney",
        "Geekydog",
        "Gemma Roman",
        "Genesis993",
        "GeorgeOtsubo",
        "Getsousa!",
        "Ghosthause",
        "GillesBone",
        "Gimetzco!",
        "Gintron",
        "Glen Brogan",
        "GordonB",
        "Gorlassar",
        "Graja",
        "Graphismart",
        "Green Devil",
        "Guillercraist",
        "GuitarAtomik",
        "GyleDesigns",
        "H.Heal",
        "Haasbroek",
        "Hamburglar4Life",
        "HandsomeJake",
        "Haragos",
        "Harantula",
        "Harzack",
        "HeyPogo",
        "Hiamovi",
        "Hittouch",
        "Hootbrush",
        "HudsonVibes",
        "Huino",
        "Hulkey",
        "Hydro74",
        "IKILO",
        "Ian Leino",
        "IdeasConPatatas",
        "Immortalized",
        "InkOne",
        "IntergalacticSheep",
        "Ionfox",
        "Italiux",
        "ItokoDesign",
        "JAZZCOLA",
        "JBaz",
        "JCMaziu",
        "JMDragunas",
        "JPThomas",
        "JUNKdraws",
        "JackBurton25",
        "JackGibberish",
        "Jaime Ugarte",
        "JalbertAMV",
        "Jehkoba",
        "Jehsee",
        "JennyParks",
        "Joannaestep",
        "Joannaestepp",
        "Joe Wright",
        "JoeConde",
        "JoeGrady",
        "JollyNihilist",
        "Jonito",
        "JoshLn",
        "Jshsee",
        "JuanFoo",
        "Jumpix",
        "KKTEE",
        "KOMBOH Creative",
        "Kasey Fleming",
        "KatHaynes",
        "KatLowryArt",
        "Kat_Haynes",
        "Katie Campbell",
        "KatieClarkArt",
        "Kellabell9",
        "Kelly McKernan",
        "Kempo24",
        "KentZonestar",
        "KindaCreative",
        "KingsandQueens",
        "KinkajouArt",
        "KoLabs",
        "Kyle Harlan",
        "Kyoki^3",
        "LAZARE",
        "LadyMorgan",
        "LagoonCreatures",
        "Lanfa",
        "Larlar",
        "Lartist",
        "Latvilous",
        "LavaLampTee",
        "Le Chardonneret",
        "Least Weasel Design",
        "Legendary Phoenix",
        "LestatPrincess",
        "Letter_Q",
        "LiRoVi",
        "Licunatt",
        "Liewrite",
        "LithiumL",
        "Logan Feliciano",
        "LooneyCartooney",
        "LukeSpicer",
        "MIKELopez",
        "MJ",
        "Ma_Lockser",
        "Made With Awesome",
        "MadeWithAwesome",
        "Malixx",
        "Mandrie",
        "Manoss1995",
        "ManuelDA",
        "Marcoapc",
        "MarianoSan",
        "Marissa.G",
        "MarkBado",
        "MarkTheGreat",
        "Marthaisbl",
        "Mathijs Vissers",
        "Mathiole",
        "Matias Bergara",
        "Matt Parsons",
        "Matt_Dearden",
        "MatteoSantos",
        "Maxman58",
        "Mazzlebee",
        "MdMbunny",
        "Mdk7",
        "MedusaD",
        "MeganLara",
        "Melee_Ninja",
        "Melkron",
        "Melonseta",
        "Michael Myers Jr.",
        "Mike Koubou",
        "Mike Wohlberg",
        "Mikey Mumble",
        "Minilla",
        "Miranda Dressler",
        "MissJane",
        "Mission Brainwash",
        "MoisEscudero",
        "MoniWolf",
        "Moon Prop House",
        "MortinfamiART",
        "Moutchy",
        "Mr Rocks",
        "Murphypop",
        "Mykelad",
        "Nados",
        "NakaCooper",
        "Naolito",
        "Narwen",
        "Nathan Stillie",
        "Natural 20 Shirts",
        "NemiMakeit",
        "Nemons",
        "Nerdy Mandy",
        "Nertee Designs",
        "Newhouse Designs",
        "NibiruHybrid",
        "Night Donuts",
        "NomadSlim",
        "Nooligan",
        "Obinsun",
        "Obvian",
        "OfficeInk",
        "Oktobear",
        "Olipop",
        "OneShoeOff",
        "PKtora",
        "Pacari",
        "Paintchips",
        "PanosStamo",
        "Pau Margaix",
        "Pengew",
        "PenguinPlot",
        "Phantom Grizzly Studios",
        "PhantomGum",
        "Phil Postma",
        "Pierrick Chevallier",
        "Pixel Pop Tees",
        "PixelBitHero",
        "PixelEyeBat",
        "PlasticBlast",
        "Pleiadi",
        "PolySciGuy",
        "Poofette",
        "Poopsmoothie",
        "PrimePremne",
        "ProlificPen",
        "Punksthetic",
        "Purrdemonium",
        "Pyne",
        "R-evolution GFX",
        "RAIDHO",
        "RBucchioni",
        "RRB",
        "RachelMSilva",
        "Raditude",
        "Raffiti",
        "Raki",
        "Ramos",
        "Randy McQuien Jr",
        "Randyotter",
        "Ratigan",
        "RazCity",
        "RebelArt",
        "RenatoF",
        "Retro Nerd Studio",
        "Retro Review",
        "RhunaArt",
        "RickThompson",
        "RicoMambo",
        "RizaPeker",
        "Robin Hxxd",
        "RobotSoda",
        "Robreepart",
        "RockyDavies",
        "Rodrigo Gafa",
        "Rookheart",
        "RoseMakesArt",
        "Rosey Cheekes",
        "RyanAstle",
        "RynoArts",
        "SOULTHROW",
        "SXStudios",
        "Salvador Anguiano",
        "SamCarterArt",
        "SarahCave",
        "SaturnTwins",
        "Scott Neilson Concepts",
        "SebbDraws",
        "SergioDoe",
        "SevenHundred",
        "Shadyjibes",
        "Shamus Beyale",
        "Shiron",
        "SilverBaX",
        "Sitchko Igor",
        "Six Eyed Monster",
        "Skullpy",
        "Snapnfit",
        "SokolSelmani",
        "Soletine",
        "SomeGuero",
        "SophieCorrigan",
        "Soulkr",
        "Spedy93",
        "Stank",
        "Ste7en Lefcourt",
        "Steve Dressler",
        "SteveOramA",
        "Steven Rhodes",
        "StevenToang",
        "StudioM6",
        "SubversiveGirl",
        "SuperEmoFriends",
        "TEEvsTEE",
        "THRASHERR",
        "Tabners",
        "TaylorRoss1",
        "Tchuk",
        "TechraNova",
        "TedDastickJr",
        "TeeKetch",
        "Tek-Man",
        "Teo Zed",
        "ThatKidWhoDraws",
        "The Grilled Bacon",
        "TheDrawbridge",
        "ThePaperCrane",
        "Theonides",
        "TimShumate",
        "TomTrager",
        "TonyCenteno",
        "Tracy Tubera",
        "TrulyEpic",
        "TsaoShin",
        "Typhoonic",
        "UnlikelyDesigns",
        "Vallina84",
        "Vanadium",
        "Velizaco",
        "VinnieDraws",
        "Vo1ture",
        "Voodrew",
        "WTW",
        "WanderingBert",
        "WaywardDoodles",
        "Wenceslao A Romero",
        "Wheels",
        "Whitebison",
        "WhosTonyRamos",
        "WinterArtwork",
        "WinterWolfDesign",
        "Wirdou",
        "Yema Yema",
        "YiannisTees",
        "Zeeee",
        "ZoelOne",
        "ZombieDollars",
        "aLittleFED",
        "adamrabalais",
        "adho1982",
        "aflagg",
        "againstbound",
        "albertocubatas",
        "alecxpstees",
        "alemaglia",
        "alliebirdseed",
        "alnavasord",
        "amanoxford",
        "amorias",
        "andyhunt",
        "angdzu",
        "angi-pants",
        "apexisy",
        "arace",
        "armoredfoe",
        "artbyjoebalde",
        "arti",
        "ashytaka",
        "astrorobyn",
        "athelstan",
        "atteoM",
        "azrafdesign",
        "bakhus",
        "barefists",
        "batang 9tees",
        "batman1138",
        "beanclam",
        "beanepods",
        "beckadoodles",
        "belial90",
        "benmitchell",
        "beware1984",
        "biggedy",
        "biggers",
        "biticol",
        "bleee",
        "bluerobot",
        "boltfromtheblue",
        "bomdesignz",
        "boostr29",
        "bubbleknight",
        "butcherbilly",
        "bykai",
        "bytesizetreasure",
        "carbine",
        "carlpearceillustrator",
        "castlepop",
        "cedriclopezf",
        "celtichammerclub",
        "cepheart",
        "chavertape",
        "chechevica",
        "chemabola8",
        "chocopants",
        "cjboucher",
        "clingcling",
        "coldfireink",
        "cpdesign",
        "craftsman",
        "crazychri1",
        "crocktees",
        "cryface",
        "cs3ink",
        "csharron",
        "csweiler",
        "cubik",
        "cumix47",
        "cyclonaut",
        "daggerdrawndesign",
        "dailenogden",
        "dalethesk8er",
        "dalgoda7",
        "dandingeroz",
        "dandstrbo",
        "danidraws",
        "danielmorris1993",
        "danirodart",
        "dann matthews",
        "dannyhaas",
        "dannyrumbl",
        "daobiwan",
        "daria rhodes",
        "darrudadesign",
        "davesongart",
        "ddjvigo",
        "decodedesignco",
        "demonigote",
        "demonigoteshirts",
        "department",
        "diegopedauye",
        "digitoonie",
        "diha",
        "dmh2create",
        "docwhiskey",
        "doodledojo",
        "dorksince83",
        "dorothytimmer",
        "dr. lupo",
        "dracoimagem",
        "draculabyte",
        "drbutler",
        "droidloot",
        "drzebra",
        "ducfrench",
        "dudey300",
        "dumbassman",
        "dumbshirts",
        "dv8sheepn",
        "dwayniac",
        "dynamitfrosch",
        "dystopix",
        "eduely",
        "edwoody",
        "elfwitch",
        "etcherSketch",
        "everdream",
        "evolvingeye",
        "eztz13",
        "fabiobottega",
        "famousafterdeath",
        "fanfreak1",
        "fatcakes",
        "florentbodart",
        "flying mouse",
        "flying piggie designs",
        "flyingmouse365",
        "flylanddesigns",
        "food one",
        "foureyedesign",
        "freeminds",
        "fychan",
        "gamepaused",
        "gaunty",
        "geekchic_tees",
        "glenlowry",
        "gloopz",
        "golden cucco",
        "goliath72",
        "goodidearyan",
        "gotoup",
        "grateful8",
        "graywrabbit",
        "greatsky",
        "griftgfx",
        "gugliottiC",
        "halfhuman",
        "harebrained",
        "hartmasl",
        "hbdesign",
        "heartjack",
        "heydale",
        "heymonster",
        "heythequickness",
        "hislla",
        "hoborobo",
        "hodgesart",
        "hugohugo",
        "hyperlixir",
        "hypertwenty",
        "ibtrav",
        "ibyes_illustration",
        "icedust",
        "identitypollution",
        "idriu95",
        "ilcalvelage",
        "illproxy",
        "ilustrata",
        "imaginaryastronaut",
        "imnos",
        "inaco",
        "inkjava",
        "isma_wayne",
        "ithrowtrainz",
        "itsdanielle91",
        "jacobcharlesdietz",
        "jamesbattershill",
        "jangosnow",
        "japu",
        "javiclodo",
        "jayf23",
        "jdarnell",
        "jeffwest",
        "jennycubs",
        "jennypark",
        "jerbing",
        "jkilpatrick",
        "jmcg",
        "jmlfreeman",
        "joefixit2",
        "johnnygreek989",
        "jonpinto",
        "jozvoz",
        "jpcoovert",
        "jpzilla",
        "jrberger",
        "jubbathehott",
        "juliancallos",
        "jun087",
        "justingammon",
        "kal5000",
        "kalgado",
        "kanoby",
        "karlangas",
        "kathudsonart",
        "katiecandraw",
        "keelhaulkate",
        "kennsing",
        "kentcribbs",
        "kgullholmen",
        "kharmazero",
        "kidleo",
        "kimhobby",
        "kittycassandra",
        "kiwifruitbird",
        "koalastudio",
        "kookylove",
        "kosmicsatellite",
        "krisren28",
        "krusemark",
        "ladymagumba",
        "lahnaloo",
        "laiman.tee",
        "lazllanes",
        "leea1968",
        "leo_queval",
        "lilliegrimm",
        "lisaveeee",
        "littlebird.bigwolf",
        "logancarroll",
        "lonepigeon",
        "losthero",
        "louisros",
        "lsimpson",
        "lucassilva",
        "lunchboxbrain",
        "machmigo",
        "mankeeboi",
        "mannypdesign",
        "manospd",
        "manoystee",
        "manuelvita96",
        "maped",
        "matpynte",
        "mattkaufenberg",
        "mattographer",
        "mattsinorart",
        "mauriciomota",
        "mauru",
        "max58",
        "meal",
        "meatsquint",
        "mekazoo",
        "melmike",
        "mephias",
        "mgraphics82",
        "michelborges",
        "michellecoffee",
        "midgerock",
        "mightyb",
        "miguelcamilo",
        "mikehandyart",
        "mikematola",
        "minerva",
        "misslys",
        "missmonster",
        "mmarcin",
        "mmatsumoto",
        "monitosbonitos",
        "most",
        "motoslave",
        "moysche",
        "mudron",
        "mydeardear",
        "mynameisace",
        "mysteryof",
        "nakedderby",
        "nanlawson",
        "nasmo",
        "natebear",
        "nayawei",
        "ndtank",
        "neninekoarts",
        "nerduniverse",
        "neverblueshirts",
        "neverbluetshirts",
        "nicebleed",
        "ninni93",
        "nippyer",
        "noemizelaya",
        "ntesign",
        "ogie1023",
        "onebluebird",
        "osmarescoto",
        "otisframpton",
        "owlhaus",
        "pacalin",
        "palitosci",
        "paulagarcia",
        "pekania",
        "perdita00",
        "pertheseus",
        "pescapin",
        "piercek26",
        "pigboom",
        "pipperx",
        "powerpig",
        "ppmid",
        "prometheus31",
        "protec",
        "pscof42",
        "pscullin",
        "pufahl",
        "pupukachoo",
        "qbfox",
        "qetza",
        "queenmob",
        "raffaus",
        "rektech",
        "renduh",
        "ricolaa",
        "risarodil",
        "robotnicc",
        "robyriker",
        "rocketman_art",
        "rocketmanart",
        "rustenico",
        "rustinco",
        "ryderdoty",
        "sakuradragon",
        "salihgonenli",
        "santanafirpo",
        "saqman",
        "scarletknightco",
        "scenestealer",
        "se7te",
        "sebasebi",
        "seventoes",
        "shavostars",
        "shirox",
        "shirtoid",
        "shoden",
        "silentOp",
        "sixamcrisis",
        "sketchboy01",
        "sleepingsky",
        "slinkstar",
        "sophieeves90",
        "soulful",
        "spaceboystudios",
        "spacemonkeydr",
        "spike00",
        "spiritgreen",
        "spookyruthy",
        "stationjack",
        "steevinlove",
        "stellica",
        "stlkid",
        "storyofthedoor",
        "strawberryquiche",
        "swankgraphics",
        "taniloo",
        "tanoshiboy",
        "teddythulu",
        "teefury",
        "theGorgonist",
        "thedicegoddess",
        "theemadhare",
        "thehookshot",
        "thekfish",
        "thirdeyeh",
        "thom2maro",
        "tiranocyrus",
        "tobefonseca",
        "tofusan",
        "tolagunestro",
        "tom burns",
        "tomkurzanski",
        "tonynichols",
        "tracybeesdale",
        "trheewood",
        "troeks",
        "ursulalopez",
        "vic_bell",
        "victorsbeard",
        "vincent gauriat",
        "vomaria",
        "vp021",
        "wagnogueira",
        "waltermck",
        "wearviral",
        "wfdj",
        "winston",
        "wotto",
        "wyrm974",
        "wytrab8",
        "xMitch",
        "xMorfina",
        "xiaobaosg",
        "yankenpop",
        "yannickglt",
        "yumemiru",
        "yumie",
        "zRiSes",
        "zackolantern",
        "zerobriant",
        "zoestanleyarts",
        "zombiemedia",
        "zula"
    ]
}
