@api_version={{$dotenv SHOPIFY_VERSION}}
@domain={{$dotenv DOMAIN}}
@shopify_token={{$dotenv SHOPIFY_TOKEN}}
###
GET https://{{domain}}.myshopify.com/admin/api/{{api_version}}/products/count.json
Content-Type: application/json
X-Shopify-Access-Token: {{shopify_token}}
