POST https://{{$dotenv SHOPIFY_NAME}}.myshopify.com/admin/api/2021-07/graphql.json
Content-Type: application/json
X-Shopify-Access-Token: {{$dotenv SHOPIFY_API_KEY}}
X-REQUEST-TYPE: GraphQL

query listWebhooks {
  webhookSubscriptions(first: 20) {
    edges {
      node {
        id
        topic
				callbackUrl
				endpoint {
          __typename
        }
      }
    }
  }
}
